import React, { PropsWithChildren, StrictMode } from "react";
import NavBar from "../Components/NavBar/NavBar";
import MaterialTheme from "@/Components/Layout/Material Theme";
import BackgroundImage from "@/Components/Layout/BackgroundImage/CotainerBackground";
import "./globals.css";

export const metadata = {
  title: "LolGuess",
  description: "Generated by create next app",
};

export const links = [
  {
    ref: "/nickname",
    content: "Nickname",
  },
  {
    ref: "/",
    content: "Skill",
  },

  {
    ref: "/splashart",
    content: "Splashart",
  },
];

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <StrictMode>
      <MaterialTheme>
        <head>
          <link rel="icon" href="/favicon.ico" sizes="any" />
        </head>
        <html>
          <body>
            <BackgroundImage />
            <NavBar links={links} />
            {children}
          </body>
        </html>
      </MaterialTheme>
    </StrictMode>
  );
}
