import React, { PropsWithChildren, StrictMode } from "react";
import NavBar from "../Components/NavBar/NavBar";
import MaterialTheme from "@/Components/Layout/Material Theme";
import "./globals.css";
import BackgroundImage from "@/Components/Layout/BackgroundImage/CotainerBackground";

export const metadata = {
  title: "LolGuess",
  description: "Generated by create next app",
};

export const links = [
  {
    ref: "/",
    content: "Champ",
  },
  {
    ref: "/title",
    content: "Title",
  },
  {
    ref: "/splashart",
    content: "SplashArt",
  },
  {
    ref: "/title",
    content: "Quote",
  },
];
export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <StrictMode>
      <MaterialTheme>
        <html>
          <body>
            <BackgroundImage />
            <NavBar links={links} />
            {children}
          </body>
        </html>
      </MaterialTheme>
    </StrictMode>
  );
}
